### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by OndroNR** [pine64/pine64_updater#2]
This source code could use instructions or automated script to compose resulting tool. Mainly how to get `zadic.exe` and `dfu-util.exe` from origin.

**Comment by gamelaster** [comment]
dfu-util shouldn't be problem to compile, but I'm bit worried about zadic. It requires Windows SDKs and mainly Windows Driver SDK, I don't know how I would do that in CI. Also maybe libusb would be good to have here

**Comment by krzysztofzawadzki** [comment]
@gamelaster Are You able to share which version of QT and libusb You are using for building?

**Comment by gamelaster** [comment]
@krzysztofzawadzki Qt it's latest 5.x version, the libusb it's probably 1.0.23.

**Comment by gamelaster** [comment]
I think we can close this, since libdfu-util and libusb is built by CI (instructions are [here](https://github.com/gamelaster/dfu-util/blob/libdfu-util/.github/workflows/build.yml)), and same for PINE64 Updater. The zadic.exe although is still compiled by myself, but since there is #19 , which will replace zadic, after that I will add instructions for building the new library.
